name: Build, Push Docker Images, and Redeploy on Render

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push backend image
      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend  # Make sure this path points to your backend Dockerfile
          push: true
          tags: |
            nishant625/rpf_backend:latest
            nishant625/rpf_backend:${{ github.sha }}

      # Build and push frontend image
      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend  # Make sure this path points to your frontend Dockerfile
          push: true
          tags: |
            nishant625/rpf_frontend:latest
            nishant625/rpf_frontend:${{ github.sha }}

      # Deploy to Render
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "${{ secrets.RENDER_SERVICE_ID }}"}' \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys